server:
 port: 8999

eureka:
  instance:
    hostname: localhost  

spring:
  application:
    name: Gateway_API_Service

  cloud:
    gateway:
      routes:

        - id: DamagedProduct-service

          uri: lb://DamagedProduct-service

          predicates:

            - Path=/ssp/**      
